
@echo off

REM !!! Generated by the fmp-cli 1.83.0.  DO NOT EDIT!

md GridMenu\Assets\3rd\fmp-xtc-gridmenu

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-gridmenu-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\GridMenu\Assets\3rd\fmp-xtc-gridmenu\
